// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeswszuuyagszkbptdik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplc3dzenV1eWFnc3prYnB0ZGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTkwNTksImV4cCI6MjA2NjczNTA1OX0.wM2v_xvYQqD2c5kbielx0kWYZ4TaBcTO7BIlRO1COAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);